// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQt4I5yMcvvSKQ7Ewlg3fWscZgIrcQHLU',
    appId: '1:465007199625:web:5534cc481f4c112e228d58',
    messagingSenderId: '465007199625',
    projectId: 'pooja-7a942',
    authDomain: 'pooja-7a942.firebaseapp.com',
    storageBucket: 'pooja-7a942.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2c57Nr23nQvxHnOQFa8rCNKHpoV4uVI',
    appId: '1:465007199625:android:ea6db19ead2c12af228d58',
    messagingSenderId: '465007199625',
    projectId: 'pooja-7a942',
    storageBucket: 'pooja-7a942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPBfx15YBFLBb1mPeDatILbSEfHBzkPGQ',
    appId: '1:465007199625:ios:6d6969073947ffe0228d58',
    messagingSenderId: '465007199625',
    projectId: 'pooja-7a942',
    storageBucket: 'pooja-7a942.firebasestorage.app',
    iosBundleId: 'com.example.pooja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPBfx15YBFLBb1mPeDatILbSEfHBzkPGQ',
    appId: '1:465007199625:ios:6d6969073947ffe0228d58',
    messagingSenderId: '465007199625',
    projectId: 'pooja-7a942',
    storageBucket: 'pooja-7a942.firebasestorage.app',
    iosBundleId: 'com.example.pooja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQt4I5yMcvvSKQ7Ewlg3fWscZgIrcQHLU',
    appId: '1:465007199625:web:b1166049885c4840228d58',
    messagingSenderId: '465007199625',
    projectId: 'pooja-7a942',
    authDomain: 'pooja-7a942.firebaseapp.com',
    storageBucket: 'pooja-7a942.firebasestorage.app',
  );
}